const configs = {
  APP_ENV: process.env.REACT_APP_ENV,
  API_DOMAIN: process.env.REACT_APP_API_DOMAIN,
  APP_USER_DOMAIN: process.env.REACT_APP_USER_DOMAIN,
  ROOT_DOMAIN_TOKEN: process.env.REACT_APP_CLIENT_ROOT_DOMAIN_TOKEN,
  AGORA_APP_ID: process.env.REACT_APP_AGORA_APP_ID,
  WEB_SOCKET_DOMAIN: process.env.REACT_APP_WEB_SOCKET_DOMAIN,
  SHOP_DOMAIN: process.env.REACT_APP_SHOP_DOMAIN,
  PRICE_TO_BONUS: process.env.REACT_APP_PRICE_TO_GET_BONUS,
  TEXT_BONUS: process.env.REACT_APP_TEXT_BONUS,
  BONUS_COLLECTION_IDS: process.env.REACT_APP_BONUS_COLLECTION_IDS,
};

export default configs;
